module.exports = {
CHANNELS: {
  SAINT: ['ID_SALON_TEXTE', 'ID_FORUM_PARENT'],
  POLLUE: ['ID_AUTRE_SALON', 'ID_AUTRE_FORUM'],
  SOUILLE: ['ID_SALON_SOUILLE', 'ID_FORUM_SOUILLE']
},

  GAINS: {
    SAINT: 0.2,
    POLLUE: 0.4,
    SOUILLE: 0.6
  },

  MIN_LENGTH: 300,
  MAX_SOUILLURE: 100
};